// Code generated by "stringer -type=Capability -output=capability_string.go"; DO NOT EDIT.

package yubico

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CapabilityOTP-1]
	_ = x[CapabilityU2F-2]
	_ = x[CapabilityCCID-4]
	_ = x[CapabilityOpenPGP-8]
	_ = x[CapabilityPIV-16]
	_ = x[CapabilityOATH-32]
	_ = x[CapabilityCTAP2-512]
}

const (
	_Capability_name_0 = "CapabilityOTPCapabilityU2F"
	_Capability_name_1 = "CapabilityCCID"
	_Capability_name_2 = "CapabilityOpenPGP"
	_Capability_name_3 = "CapabilityPIV"
	_Capability_name_4 = "CapabilityOATH"
	_Capability_name_5 = "CapabilityCTAP2"
)

var (
	_Capability_index_0 = [...]uint8{0, 13, 26}
)

func (i Capability) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _Capability_name_0[_Capability_index_0[i]:_Capability_index_0[i+1]]
	case i == 4:
		return _Capability_name_1
	case i == 8:
		return _Capability_name_2
	case i == 16:
		return _Capability_name_3
	case i == 32:
		return _Capability_name_4
	case i == 512:
		return _Capability_name_5
	default:
		return "Capability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
