// Code generated by "stringer -type=FormFactor -output=form_factor_string.go"; DO NOT EDIT.

package yubico

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FormFactorUnknown-0]
	_ = x[FormFactorUSBAKeychain-1]
	_ = x[FormFactorUSBANano-2]
	_ = x[FormFactorUSBCKeychain-3]
	_ = x[FormFactorUSBCNano-4]
	_ = x[FormFactorUSBCLightning-5]
	_ = x[FormFactorUSBABiometricKeychain-6]
	_ = x[FormFactorUSBCBiometricKeychain-7]
}

const _FormFactor_name = "FormFactorUnknownFormFactorUSBAKeychainFormFactorUSBANanoFormFactorUSBCKeychainFormFactorUSBCNanoFormFactorUSBCLightningFormFactorUSBABiometricKeychainFormFactorUSBCBiometricKeychain"

var _FormFactor_index = [...]uint8{0, 17, 39, 57, 79, 97, 120, 151, 182}

func (i FormFactor) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_FormFactor_index)-1 {
		return "FormFactor(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FormFactor_name[_FormFactor_index[idx]:_FormFactor_index[idx+1]]
}
