// Code generated by "stringer -type=Command,CapabilityFlag,Error,KeepaliveStatusCode -output=consts_string.go"; DO NOT EDIT.

package ctaphid

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CTAPHID_MSG-3]
	_ = x[CTAPHID_CBOR-16]
	_ = x[CTAPHID_INIT-6]
	_ = x[CTAPHID_PING-1]
	_ = x[CTAPHID_CANCEL-17]
	_ = x[CTAPHID_ERROR-63]
	_ = x[CTAPHID_KEEPALIVE-59]
	_ = x[CTAPHID_WINK-8]
	_ = x[CTAPHID_LOCK-4]
	_ = x[CTAPHID_VENDOR_FIRST-64]
	_ = x[CTAPHID_VENDOR_LAST-127]
}

const (
	_Command_name_0 = "CTAPHID_PING"
	_Command_name_1 = "CTAPHID_MSGCTAPHID_LOCK"
	_Command_name_2 = "CTAPHID_INIT"
	_Command_name_3 = "CTAPHID_WINK"
	_Command_name_4 = "CTAPHID_CBORCTAPHID_CANCEL"
	_Command_name_5 = "CTAPHID_KEEPALIVE"
	_Command_name_6 = "CTAPHID_ERRORCTAPHID_VENDOR_FIRST"
	_Command_name_7 = "CTAPHID_VENDOR_LAST"
)

var (
	_Command_index_1 = [...]uint8{0, 11, 23}
	_Command_index_4 = [...]uint8{0, 12, 26}
	_Command_index_6 = [...]uint8{0, 13, 33}
)

func (i Command) String() string {
	switch {
	case i == 1:
		return _Command_name_0
	case 3 <= i && i <= 4:
		i -= 3
		return _Command_name_1[_Command_index_1[i]:_Command_index_1[i+1]]
	case i == 6:
		return _Command_name_2
	case i == 8:
		return _Command_name_3
	case 16 <= i && i <= 17:
		i -= 16
		return _Command_name_4[_Command_index_4[i]:_Command_index_4[i+1]]
	case i == 59:
		return _Command_name_5
	case 63 <= i && i <= 64:
		i -= 63
		return _Command_name_6[_Command_index_6[i]:_Command_index_6[i+1]]
	case i == 127:
		return _Command_name_7
	default:
		return "Command(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CAPABILITY_WINK-1]
	_ = x[CAPABILITY_CBOR-4]
	_ = x[CAPABILITY_NMSG-8]
}

const (
	_CapabilityFlag_name_0 = "CAPABILITY_WINK"
	_CapabilityFlag_name_1 = "CAPABILITY_CBOR"
	_CapabilityFlag_name_2 = "CAPABILITY_NMSG"
)

func (i CapabilityFlag) String() string {
	switch {
	case i == 1:
		return _CapabilityFlag_name_0
	case i == 4:
		return _CapabilityFlag_name_1
	case i == 8:
		return _CapabilityFlag_name_2
	default:
		return "CapabilityFlag(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_INVALID_CMD-1]
	_ = x[ERR_INVALID_PAR-2]
	_ = x[ERR_INVALID_LEN-3]
	_ = x[ERR_INVALID_SEQ-4]
	_ = x[ERR_MSG_TIMEOUT-5]
	_ = x[ERR_CHANNEL_BUSY-6]
	_ = x[ERR_LOCK_REQUIRED-10]
	_ = x[ERR_INVALID_CHANNEL-11]
	_ = x[ERR_OTHER-127]
}

const (
	_Error_name_0 = "ERR_INVALID_CMDERR_INVALID_PARERR_INVALID_LENERR_INVALID_SEQERR_MSG_TIMEOUTERR_CHANNEL_BUSY"
	_Error_name_1 = "ERR_LOCK_REQUIREDERR_INVALID_CHANNEL"
	_Error_name_2 = "ERR_OTHER"
)

var (
	_Error_index_0 = [...]uint8{0, 15, 30, 45, 60, 75, 91}
	_Error_index_1 = [...]uint8{0, 17, 36}
)

func (i Error) String() string {
	switch {
	case 1 <= i && i <= 6:
		i -= 1
		return _Error_name_0[_Error_index_0[i]:_Error_index_0[i+1]]
	case 10 <= i && i <= 11:
		i -= 10
		return _Error_name_1[_Error_index_1[i]:_Error_index_1[i+1]]
	case i == 127:
		return _Error_name_2
	default:
		return "Error(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STATUS_PROCESSING-1]
	_ = x[STATUS_UPNEEDED-2]
}

const _KeepaliveStatusCode_name = "STATUS_PROCESSINGSTATUS_UPNEEDED"

var _KeepaliveStatusCode_index = [...]uint8{0, 17, 32}

func (i KeepaliveStatusCode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_KeepaliveStatusCode_index)-1 {
		return "KeepaliveStatusCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KeepaliveStatusCode_name[_KeepaliveStatusCode_index[idx]:_KeepaliveStatusCode_index[idx+1]]
}
